
select * from CATEGORY;



sp_help category


ALTER TABLE CATEGORY
ADD CATEGORY INT IDENTITY(1,1) PRIMARY KEY;



select * from product;


SELECT P.ID_PRODUCT, P.NAME_PRODUCT, P.PRICE, P.QUANTITY, P.DESCRIPTION, 
C.NAME_CATEGORY AS NAME_CATEGORY, CASE WHEN AVAILABLE='0' THEN 'NO DISPONIBLE' ELSE 'DISPONIBLE' END AS AVAILABLE, URL_IMAGEN FROM PRODUCT P 
JOIN CATEGORY C ON C.ID_CATEGORY=P.ID_CATEGORY


